version: '3.5'
services:
    php:
        image: rroubaix/laravel-kubernetes:latest
        restart: always
        ports:
            - "8000:80"
        environment:
            - APP_KEY="base64:azc80yCbqs5/c2r7YsxzwKgisjjpCc0PU4VGH96023c="
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_PORT=3306
            - DB_HOST=mysql
            - DB_DATABASE=local_db
            - DB_USERNAME=admin
            - DB_PASSWORD=password
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=rootpassword
            - MYSQL_DATABASE=local_db
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=password
